### ISSUE TITLE
TemplateDoesNotExist at /cm_search/

### ISSUE THREAD

**Issue by bsesic** [wisslab/judaicalink-labs#13]
CM Search does not work.

Request Method: | GET
-- | --
http://localhost:8000/cm_search/
3.0.5
TemplateDoesNotExist
cm_search/search_index.html
/usr/local/lib/python3.7/site-packages/django/template/loader.py in get_template, line 19
/usr/local/opt/python/bin/python3.7
3.7.7
['/Users/benni/coding/judaicalink/judaicalink-labs/labs',  '/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',  '/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7',  '/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages',  '/usr/local/lib/python3.7/site-packages/geos',  '/usr/local/Cellar/matplotlib/2.2.3/libexec/lib/python3.7/site-packages',  '/usr/local/Cellar/protobuf/3.11.4/libexec/lib/python3.7/site-packages']
Wed, 13 May 2020 17:12:51 +0200

Using engine django:

django.template.loaders.filesystem.Loader: /Users/benni/coding/judaicalink/judaicalink-labs/labs/templates/cm_search/search_index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.7/site-packages/django/contrib/admin/templates/cm_search/search_index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.7/site-packages/django/contrib/auth/templates/cm_search/search_index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /Users/benni/coding/judaicalink/judaicalink-labs/labs/core/templates/cm_search/search_index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /Users/benni/coding/judaicalink/judaicalink-labs/labs/backend/templates/cm_search/search_index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /Users/benni/coding/judaicalink/judaicalink-labs/labs/search/templates/cm_search/search_index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /Users/benni/coding/judaicalink/judaicalink-labs/labs/lodjango/templates/cm_search/search_index.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.7/site-packages/compressor/templates/cm_search/search_index.html (Source does not exist)

**Comment by sarafischer** [comment]
probably missing the app-registration of cm_search in labs/labs/settings.py

**Comment by bsesic** [comment]
Erledigt.
