### ISSUE TITLE
evtl. Animation in Judaicalink web noch ändern?

### ISSUE THREAD

**Issue by bsesic** [wisslab/judaicalink-labs#26]
Ort: Homepage Web 
Status: VORERST NICHT NÖTIG

**Comment by bsesic** [comment]
Was soll daran geändert werden?

**Comment by PatriciaKaluza** [comment]
War nur mal eine Fage, aber vorerst passt das so. :D

**Comment by bsesic** [comment]
Ich denke nicht, dass die Animation geändert werden muss. Sie sieht gut aus. Eine Frage ist noch, ob wir ein statisches Bild für Smartphones einbinden.
