### ISSUE TITLE
Animation Format Anzeige anpassen

### ISSUE THREAD

**Issue by bsesic** [wisslab/judaicalink-labs#27]
Animation funktioniert auf Smartphone nicht. [Chrome]
Ort: Homepage Web 
Status: DONE -> muss noch getestet werden ob es jetzt wirklich besser geworden ist 29.06

**Comment by bsesic** [comment]
Es muss geklärt werden, ob Chrome auf dem Smartphone die Animation überhaupt unterstützt.

**Comment by PatriciaKaluza** [comment]
Das Problem sollte schon gefixt sein.
