### ISSUE TITLE
Nachvollziehbarer machen wo man sich befindet, 

### ISSUE THREAD

**Issue by bsesic** [wisslab/judaicalink-labs#29]
web, data, labs, evtl. tags in der sidebar unter background vllt
Ort: Design Allgemein

**Comment by bsesic** [comment]
Die Tags sind gerade nicht sinnvoll. Wir haben dafür die Farben. Eventuell bekommt das der User gar nicht mit wo man ist.
Daher sollten die Tags raus. @PatriciaKaluza

**Comment by PatriciaKaluza** [comment]
Die Tags sollen raus? Ok es gab mal eine Überlegung, dass die tags auf die jeweiligen Seiten verlinken sollen. Aber die momentane Umsetzung ist noch nicht perfekt das stimmt.

**Comment by bsesic** [comment]
Wir haben uns gefragt ob es viel bringt, zumal dem User das eventuell egal ist, zumal auch die Farben darauf hinweisen. Aber du kannst gerne eine funktionierende Version vorschlagen.

**Comment by PatriciaKaluza** [comment]
Da bin ich ganz eurer Meinung, dann würde ich die Tags doch einfach entfernen.
