### ISSUE TITLE
Design concept 

### ISSUE THREAD

**Issue by PatriciaKaluza** [wisslab/judaicalink-labs#3]
We still need to think about a concrete design concept
First idea was to make the theme red and blue colors (originally blue and yellow)
Julika and I will make a mockup for it

**Comment by PatriciaKaluza** [comment]
the design will be based on [https://www.ub.uni-frankfurt.de/judaica3/home.html](url)

**Comment by PatriciaKaluza** [comment]
### First mockup
![9_MockUp](https://user-images.githubusercontent.com/59728342/75474237-e7f85700-5996-11ea-8d51-3f1632a7ae38.png)

**Comment by PatriciaKaluza** [comment]
### Navbar (in Labs):
1. will only contain the apps for labs. The footer will contain everything else.
2. should be responsive (use of JS) https://freefrontend.com/css-toggle-menus/

**Comment by julstan** [comment]
**Our current concept for the design of JudaicaLink Labs**

Regular Design:
![MockUp_regular](https://user-images.githubusercontent.com/59728338/75562377-c35cb780-5a48-11ea-9ad9-4db7254c1842.png)

Hidden Menu:
![MockUp_hiddenMenu](https://user-images.githubusercontent.com/59728338/75562415-d7081e00-5a48-11ea-9c01-311c751a7525.png)

![MockUp](https://user-images.githubusercontent.com/59728338/75562455-e9825780-5a48-11ea-8b5a-ee89c86c1bce.png)

![MockUp_Analysis](https://user-images.githubusercontent.com/59728338/75562516-fb63fa80-5a48-11ea-8e7f-5ad0bb0cfac8.png)


A possible design for smartphones

![1_Smartphone_MockUp](https://user-images.githubusercontent.com/59728338/75562546-0c147080-5a49-11ea-9000-e16aa7a74808.png)


![2_Smartphone_MockUp](https://user-images.githubusercontent.com/59728338/75562558-0fa7f780-5a49-11ea-9f49-d8b72e8f91f3.png)

**Comment by kaiec** [comment]
Wie wäre es, wenn wir das Design für das Menü vom FID übernehmen, dann ist es einheitlicher und wir haben eine Baustelle weniger.

Die Kopfzeile fände ich schmaler besser, auch wenn das Logo dabei kleiner wird. Alternativ könnte man es in der eingeklappten Version wesentlich schmaler machen. Es wird auf jeden Fall Anwendungen geben, bei denen wir möglichst viel Platz brauchen. Und gerade bei Smartphones dürfte das derzeit viel Platz wegnehmen.

Das Logo würde ich ohne grauen Hintergrund machen, ist erstens wieder näher am FID und zumindest in der eingeklappten Version sieht das graue Eck komisch aus.

Der Header wirkt unruhig durch die unterschiedlichen Schriftgrößen und vor allem die unterschiedliche Höhe. LABS muss horizontal mittig auf der gleichen Höhe wie das Logo sein. JudaicaLink eventuell auch, aber irgendwie passt das nicht. Wie wäre ein einzelner Schriftzug rechts, der sich für www und labs unterscheidet?

Struktur mit dem Footer finde ich interessant, wie würde dann analog die www site aussehen?

**Comment by PatriciaKaluza** [comment]
Hier haben wir jetzt versucht die angesprochenen Punkte umzusetzen. Auch die Schriftart und das Logo wurden an FID angepasst. Hier ist das Logo jetzt wieder auf der linken Seite, aber die Kopfzeile ist um einiges strukturierter.

Mit Menü:
![14_MockUp](https://user-images.githubusercontent.com/59728342/75882960-7f8bf880-5e22-11ea-85b4-22ba4467e261.png)

Ausgeblendetes Menü:
![15_MockUp](https://user-images.githubusercontent.com/59728342/75882966-84e94300-5e22-11ea-890d-fdb3424b9597.png)

**Comment by kaiec** [comment]
Blauer Leuchteffekt ist vermutlich ähnlich einzuordnen, wie Farbverlauf und Schlagschatten, also ganz klar: geil :-D 

Allerdings scheint es den Glow im neuen Layout nicht mehr zu geben, das Portal wird ja in Kürze auch relauncht, der Link oben sollte dafür aktuell sein: https://www.ub.uni-frankfurt.de/judaica3/home.html 

Ich würde mal probieren, das Logo noch etwas kleiner zu machen, Schriftzug JudaicaLink mit etwas mehr Abstand (aktuell klebt es am Logo) rechts daneben, Labs rechtsbündig darunter, in kleinerer Schrift weiß auf blau (also invertiert), so dass es wie ein Label aussieht, eventuell labs auch in Kleinbuchstaben oder Großbuchstaben, so dass es wie ein grafisches Element wirkt.

Wir sind auf jeden Fall in der richtigen Richtung unterwegs.

**Comment by PatriciaKaluza** [comment]
Meinen Sie, dass der Hintergrund bei dem Labs oder nur der Schriftrahmen blau sein soll?
![1_LOGO](https://user-images.githubusercontent.com/59728342/76107912-e99ace00-5fd9-11ea-998e-43591cbdd4b2.png)
Hier nur der Schriftrahmen blau (gefällt mir persönlich nicht so sehr):
![2_LOGO](https://user-images.githubusercontent.com/59728342/76107920-ec95be80-5fd9-11ea-8ccc-4f2abb5af4df.png)
![3_LOGO](https://user-images.githubusercontent.com/59728342/76107925-ef90af00-5fd9-11ea-861e-50b80bb25104.png)
![4_LOGO](https://user-images.githubusercontent.com/59728342/76107934-f28b9f80-5fd9-11ea-8695-3e51292fe64f.png)
Hier jetzt nochmal der Größenvergleich, hier finde ich das Logo auch am gelungensten:
![5_LOGO](https://user-images.githubusercontent.com/59728342/76107942-f5869000-5fd9-11ea-8aa1-1978efa6dc43.png)

Was sagen Sie zu der Schriftart? Handelt sich um Calibri Text, ist eher die erste standard Schriftart, kommt jedoch der Schriftart vom FID sehr nahe.

**Comment by PatriciaKaluza** [comment]
Hier etwas andere Ansätze:
![6_LOGO](https://user-images.githubusercontent.com/59728342/76113402-5ca94200-5fe4-11ea-8fb1-126d29a05b37.png)
![7_LOGO](https://user-images.githubusercontent.com/59728342/76113409-60d55f80-5fe4-11ea-9aa2-345d7b6cfa40.png)
![8_LOGO](https://user-images.githubusercontent.com/59728342/76113423-659a1380-5fe4-11ea-937f-9b986c0c1762.png)

**Comment by kaiec** [comment]
Hintergrund, nicht Schriftrahmen. Super, gefällt mir sehr gut, auf jeden Fall Hintergrund bündig mit Schrift. Das große Beispiel finde ich gut, auch mit der Schräge und den Kleinbuchstaben. Ich würde die labs Schrift kleiner machen und mehr Rand rechts lassen, dann stellt sich die Frage der Ausrichtung auch nicht mehr (Rand k bündig mit blauem Kasten). Unterkante labs-label bündig mit der unteren Stern-Linie. Oberkante Kleinbuchstaben u in JudaicaLink (Mittelinie oder x-Linie) bündig mit der oberen Stern-Linie. Abstand Judaicalink - Labs nach Augenmaß, ich denke ein kleines bisschen mehr als im Bild, aber nicht viel, in den Beispielen oben ist es schon zu viel.

Ist die Schräge parallel zur Stern-Linie? Sollte sie auch sein.

Zur Schrift habe ich gerade keine Meinung, kann man auf jeden Fall erst mal so machen.

Bleibt noch die Frage, was wir mit der www site machen. Anderes Label? Oder ohne Label, dann mit größerer Schrift? Wie wäre es, tatsächlich den Servernamen da rein zu machen, dann kommt in Pubby "data" rein und auf der Hauptseite "web" oder "www" (oder ein anderer Name). Aktuell läuft die Hauptseite ja unter http://judaicalink.org, das würden wir dann natürlich ändern.

**Comment by PatriciaKaluza** [comment]
Das sollte so von der Ausrichtung her passen:
![Final_Logo](https://user-images.githubusercontent.com/59728342/76165271-e75d7e80-6155-11ea-917c-fcd115ec1569.png)

**Comment by kaiec** [comment]
Ich dachte, es wäre schwarz ;-) Ich finde es super so. Also ab an die Produktion, die Server heißen web, data und labs. Abstand rechts und links im blauen Kasten gleich, bezogen auf die untere Kante (unteres labs und web sehen einigermaßen korrekt aus). Label-breite ist demnach je nach Text unterschiedlich. Produzieren Sie als nächstes reine HTML Seiten, die wir dann in Pubby, Hugo und Django einbauen können. Hier sind Beispielseiten, die Sie entsprechend stylen können:

- http://www.judaicalink.org/news/experimental-search-online/
- http://data.judaicalink.org/data/html/jre/Hause_Benedict
- http://labs.judaicalink.org/lod/grid/data/yivo/Moscow

Letzteres als Beispiel für eine Seite, die viel Platz braucht, da sollte nur noch eine ganz kleine Leiste oben bleiben.
