### ISSUE TITLE
Hamburger Menü Button bei labs in smartphoneformat nicht gleich wie in web.

### ISSUE THREAD

**Issue by bsesic** [wisslab/judaicalink-labs#31]
Grund konnte bis jetzt nicht herausgefunden werden, Code ist eig identisch.
Jedoch ist das Problem wieder browserabhängig
Status: DONE 29.06

**Comment by bsesic** [comment]
Ist das Problem jetzt geklärt?

**Comment by PatriciaKaluza** [comment]
Das Problem ist jetzt geklärt.
