### ISSUE TITLE
Analytics einbinden

### ISSUE THREAD

**Issue by bsesic** [wisslab/judaicalink-labs#37]

**Comment by kaiec** [comment]
Was eigenes oder Google Analytics?

**Comment by bsesic** [comment]
Wir wollten eigentlich Piwik. Google Analytics finde ist hingegen sehr einfach einzubinden, macht aber eventuell Probleme mti der DSGVO. Man kann aber auch etwas eigenes nehmen. Da gibt es auch Django Bibliotheken dafür.

**Comment by kaiec** [comment]
Was integriertes in Django fände ich am besten, um die Komplexität gering zu halten.

**Comment by bsesic** [comment]
Matomo ist eingebunden.
